### ISSUE TITLE
Undentified Developer

### ISSUE THREAD

**Issue by isaacimagine** [MegaApuTurkUltra/Scratch-Thumbnail-Changer#1]
Whenever I try to open up the file this pops up: 
![screen shot 2016-02-05 at 5 31 51 pm](https://cloud.githubusercontent.com/assets/11269848/12852271/702cb4d6-cc2e-11e5-9fb0-0880dc2e3b9d.png)
I was wondering if you could figure out a way a way to identify yourself so the program.

**Comment by MegaApuTurkUltra** [comment]
You can, by paying lots of money for CA signing. I'd rather not. Change your mac settings to allow unsigned programs.

**Comment by isaacimagine** [comment]
ok
