### ISSUE TITLE
InvocationTargetException

### ISSUE THREAD

**Issue by TheInitializer** [MegaApuTurkUltra/Scratch-Thumbnail-Changer#3]
https://gist.github.com/TheInitializer/f87c06267f3410859d1f5d5013e69873

Fedora 23 Workstation 64-bit

**Comment by MegaApuTurkUltra** [comment]
java.awt.HeadlessException means you don't have a screen. But, you can still use the command line version :package:  
See the releases page for the download and instructions

**Comment by TheInitializer** [comment]
I have a screen... I just ran it from the command line because double clicking didn't work :package: 

I'll try the command line version

**Comment by MegaApuTurkUltra** [comment]
Well Java doesn't seem to think you have a screen. 

Does the stack trace contain any details? The top line should say something like

```
Exception in thread "main" java.SomethingException: <Reason for exception here>
```

Your stack trace seems to be missing that line.

Also, what version of Java do you have? You may have a version that didn't ship with graphics libraries.

**Comment by TheInitializer** [comment]
I just downloaded java yesterday.

And the cmdline version works, so nvm :package:
